### ISSUE TITLE
Issues With Enumerated Values

### ISSUE THREAD

**Issue by ddeppner** [googleads/google-ads-php#38] opened 2019-03-16 22:18 UTC
I'm having difficulties working with enumerated fields using the PHP libraries.

For example, a query like this:

$query = 'select ... ad_group_criterion.quality_info.post_click_quality_score ' .
                 'from ad_group_criterion where ... ';

In this example, when I call ->getAdGroupCriterion()->getQualityInfo()->getPostClickQualityScore() it returns the integer value.  There is no getter that returns the enumerated value as a string.

Of course if I know I'm dealing with a particular field, I can manually use the V1/Enums/QualityScoreBucketEnum/QualityScoreBucket class to get at the constants.  But that's not useful for translating from int values back to the string values.  It requires some work to go backwards to determine what those are (ReflectionClass->getConstants()?) or hard coding everything.

And what if I'm writing more abstract code that should be able to determine the string values for *any* enumerated field that is returned?  For example, I want to write a generic result dump method which can take any query and output human readable tables, which is especially helpful during debugging.  In that case, I need the code to be able to determine whether a field is enumerated, and look up the string values for correct output.

If I use the GoogleAdsFieldService class to query what the int => string translations should be, the PHP libraries also prevent it from working.  I can select name, enum_values where name='ad_group_criterion.quality_info.post_click_quality_score'...  But when I walk through the accessor methods and get to ->getEnumValues(), it returns an iterator with the string values out of order, so there's still no way to determine the integer keys that match each string value.  It really seems to me that if there's a PHP wrapper around the enum_values returned from the FieldService, it should clearly present a method of determining the proper mappings.  Or just preserve the keys when presenting those strings via the getEnumValues() method, so they can easily be determined with a iterator_to_array() call to create a lookup table.

Seems like the next thing I'll try is querying the data_url of the field, determining the Enum class if there is one based on that, and then using ReflectionClass->getConstants() to get at the int to string mappings.  Very convoluted though.

I'd actually argue that returning the int value of these fields is problematic, since the numeric value is meaningless, and has to be translated into something meaningful in EVERY case where it will be used in a program.  Also, when using GAQL, we don't specify the values we're filtering for in a WHERE clause with the int.  We use the string which actually carries the meaning of the field.  Why don't we get those same values back?  I would rather the enumerated strings be returned, and then we could look up the int if we really cared (which would just about never happen).  Returning the int just makes code working with query results more convoluted and harder to understand.  We don't return the numeric representation of other non-int fields.  We don't return the sequence of ints that make up a string, and force the user to translate.  (At least not since the 1960s...)  Why do it for enum fields?

Is there some other brilliant way to achieve this that I'm just missing?  Have looked over the examples and dug through a lot of the library and not figured it out yet.

**Comment by Raibaz** [comment] 2019-03-18 08:42
Hi, and first of all thanks for the detailed explanation.

This is an issue we've been aware of for some time now, and it was caused by an issue in how PHP classes were generated from protocol buffers.

It has been recently fixed by [this PR](https://github.com/protocolbuffers/protobuf/pull/5342) being merged in the protobuf library, and the release containing the fix came out only a couple of weeks ago.

We are already working to integrate this fix in the next release of this client library, which is going to address the problem and allow you to get enum value names from their integer values.

Hope this helps.

**Comment by chiragvels** [comment] 2019-04-11 12:54
Hi @Raibaz,

Any time soon we can have this fix.

Same issue with CampaignStatus or Any Status ENUMs.

Thanks,

**Comment by Raibaz** [comment] 2019-04-11 13:20
This is scheduled for release in the next version of the client library, which is due around the end of April.

Sorry for the inconvenience and thanks for the patience.

**Comment by Raibaz** [comment] 2019-05-01 20:05
All enums now have a `name` and a `value` static function to convert between enum constant name and integer value and viceversa.

**Closed by Raibaz** 2019-05-01 20:05 UTC
