### ISSUE TITLE
 How to access Google Ads API using a Google workspace account (which is not  a gmail account)

### ISSUE THREAD

**Issue by manishkvaish** [googleads/google-ads-php#662] opened 2021-10-12 17:24 UTC
Hi,

My Client has a google workspace account (which obviously is not a Gmail account), He has created a  Google app using this workspace account, along with OAuth credentials from Google Cloud console with enabling Google Ads API .
The Google Ads Manager account, he has, is also associated with the same Google workspace account and has got Customer Id and Developer token with it.
Now with these Oauth credentials, customer Id, and Developer token I am trying to invoke GenerateKeywordIdeas() method, but getting the following Error:
" **Caller does not have permission" - User Denied Access**

Please tell me what is the way to tackle this issue.

**Comment by AnashOommen** [comment] 2021-10-12 17:47
If you can turn logging on and share the request ID, we can take a look.
There aren't any special steps than the ones you have shared.

**Comment by fiboknacky** [comment] 2021-10-13 10:31
Your developer token is not approved yet. Please visit [this guide](https://developers.google.com/google-ads/api/docs/first-call/dev-token?hl=en) for the details.
Feel free to reach out to the team on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api). They'll help you through all the steps required for using the Google Ads API.

As the issue is not related to the client library, I'll close this for now.

**Closed by fiboknacky** 2021-10-13 10:31 UTC
Labels: enhancement, triage

**Comment by fiboknacky** [comment] 2021-10-14 15:08
So, you've resolved the developer token issue already? If so and the issue is a separate one, could you file a new issue please?

**Comment by manishkvaish** [comment] 2021-10-15 06:13
Thank You fiboknacky
