### ISSUE TITLE
No information is being passed into the logger

### ISSUE THREAD

**Issue by jamiehd** [googleads/google-ads-php#43] opened 2019-03-24 11:53 UTC
I am currently using version 1.0 of the library, but I am unable to get any information passed into my provided logger.

I am defining the logger in this manner:

`
    public function make(): GoogleAdsClient
    {
        $oAuth2Credential = (new OAuth2TokenBuilder())
            ->withClientId($this->client_id)
            ->withClientSecret($this->client_secret)
            ->withRefreshToken($this->refresh_token)
            ->build();

        $clientBuilder = (new GoogleAdsClientBuilder())
            ->withDeveloperToken($this->developer_token)
            ->withOAuth2Credential($oAuth2Credential)
             ->withLogger($this->logger)
            ->withLogLevel(LogLevel::DEBUG);
        
        return $clientBuilder->build();
    }

I am using exactly the same logger with the old soap library (googleads/googleads-php-lib) and I am getting logs every time a request is made.

Am I doing something wrong or is there an issue with the library? I would expect every request to be passed into the logger with a log level of debug.

Thanks
`

**Comment by fiboknacky** [comment] 2019-03-24 16:36
Hi,

How did you create `$this->logger`?

Best,
Knack

**Comment by jamiehd** [comment] 2019-03-24 17:17
After some further debugging it appears that if the request is made while running in the console then it correctly logs, but it if is made as part of a web request it does not. Is this intended behaviour?

I can provide the source of the logger if you would like, but I have also been able to replicate the issue with a logger that does nothing but echoing out the provided logs.

Thanks

**Comment by fiboknacky** [comment] 2019-03-24 22:50
I'm not sure what you mean by part of a web request. Do you mean making a request as a part of web application?
If so, it depends on your logging configuration and other settings of your web application too. I believe it should [default to STDERR](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V1/LoggerFactory.php#L44).

The logger in this library is provided in very similar way of that in the SOAP library.

Best,
Knack

**Comment by jamiehd** [comment] 2019-03-25 09:03
What I mean is if I run php myscript.php from the command line it logs, whereas if I visit mysite.com/myscript.php it does not.

I know it defaults to stderr but surely passing in a custom logger that logs somewhere else should work? I am using the same logger with your old soap library and that is logging correctly for both web requests and command line.

**Comment by fiboknacky** [comment] 2019-03-25 09:18
Yes, it should work. So can you show your code here?
The only difference I can think of is the difference of logger name in the config file, which shouldn't have any effect if you create your own logger.

**Comment by jamiehd** [comment] 2019-03-25 09:28
I have created a very simple logger that can demonstrate the issue:

<?php

namespace App;


use Psr\Log\LoggerInterface;

class LoggerTest implements LoggerInterface
{

    public function emergency($message, array $context = array())
    {
        $this->log('emergency', $message, $context);
    }

    public function alert($message, array $context = array())
    {
        $this->log('alert', $message, $context);
    }

    public function critical($message, array $context = array())
    {
        $this->log('critical', $message, $context);
    }

    public function error($message, array $context = array())
    {
        $this->log('error', $message, $context);
    }

    public function warning($message, array $context = array())
    {
        $this->log('warming', $message, $context);
    }

    public function notice($message, array $context = array())
    {
        $this->log('notice', $message, $context);
    }

    public function info($message, array $context = array())
    {
        $this->log('info', $message, $context);
    }

    public function debug($message, array $context = array())
    {
        $this->log('debug', $message, $context);
    }

    public function log($level, $message, array $context = array())
    {
        printf('%s %s', $level, $message);
        exit('LOGGER WAS CALLED!!');
    }
}

If I run the script from the command line I get the following: 
debug Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v1.services.KeywordPlanIdeaService/GenerateKeywordIdeas", ClientCustomerId: 5446280327, RequestId: "2Ji85Ps7Kwdj2htVVfQj0g", IsFault: 0, FaultMessage: "None"LOGGER WAS CALLED!!

If I call exactly the same php script from a web browser there is no output and the script does not exit.

**Comment by fiboknacky** [comment] 2019-03-25 10:42
Can you also show your code that you use to run on your web browser as well?
And did you try setting the logger to write into a file?

**Comment by jamiehd** [comment] 2019-03-25 10:55
It is exactly the same code. I didn't try setting it to write to a file, but the exit statement should execute no matter where it is writing.

**Comment by fiboknacky** [comment] 2019-03-25 11:26
I know that it's exactly the same code, but could you please share that?
As I don't see your code, I cannot help any further. Perhaps, there might be some parts that I didn't think of before, that may be the cause of this issue.

Thank you.

**Comment by jamiehd** [comment] 2019-03-25 11:29
Hi fibonacky,

Which part would you like to see? Are you interested in the construction of the GoogleAdsClient or all parts of the request? It is difficult to supply a complete set of code as it is being used within a framework.

**Comment by fiboknacky** [comment] 2019-03-25 11:33
Basically, the part that you construct the GoogleAdsClient and the part that you send a request to the Google Ads API server.

From what you describe, it's highly likely that your log isn't called when you use it in the framework.

**Comment by jamiehd** [comment] 2019-03-25 11:37
The start of the request is this:

        $request = $this->googleAdsClientFactory->make()->getKeywordPlanIdeaServiceClient();


The content of googleAdsClientFactory is this:

    <?php
    
    namespace App\Services\GoogleAds\ApiV2;
    
    use Google\Ads\GoogleAds\Lib\OAuth2TokenBuilder;
    use Google\Ads\GoogleAds\Lib\V1\GoogleAdsClient;
    use Google\Ads\GoogleAds\Lib\V1\GoogleAdsClientBuilder;
    use Psr\Log\LoggerInterface;
    use Psr\Log\LogLevel;
    
    class GoogleAdsClientFactory
    {
        /**
         * @var string
         */
        private $developer_token;
        /**
         * @var string
         */
        private $client_id;
        /**
         * @var string
         */
        private $client_secret;
        /**
         * @var string
         */
        private $refresh_token;
        /**
         * @var LoggerInterface
         */
        private $logger;
    
        public function __construct(
            string $developer_token,
            string $client_id,
            string $client_secret,
            string $refresh_token,
            LoggerInterface $logger = null
        )
        {
            $this->developer_token = $developer_token;
            $this->client_id = $client_id;
            $this->client_secret = $client_secret;
            $this->refresh_token = $refresh_token;
            $this->logger = $logger;
        }
    
        public function make(): GoogleAdsClient
        {
            $oAuth2Credential = (new OAuth2TokenBuilder())
                ->withClientId($this->client_id)
                ->withClientSecret($this->client_secret)
                ->withRefreshToken($this->refresh_token)
                ->build();
    
            $clientBuilder = (new GoogleAdsClientBuilder())
                ->withDeveloperToken($this->developer_token)
                ->withOAuth2Credential($oAuth2Credential);
    
            if ($this->logger) {
                $clientBuilder
                    ->withLogger($this->logger)
                    ->withLogLevel(LogLevel::DEBUG);
            }
    
            return $clientBuilder->build();
        }
    }

I have confirmed the logger is defined by adding the following into my make method:
            var_dump($this->logger); exit;
Which has the following output:
/home/vagrant/Code/ad7/api/app/Services/GoogleAds/ApiV2/GoogleAdsClientFactory.php:62:
object(App\LoggerTest)[1033]

Please let me know if you would like any more information.

Thanks

**Comment by fiboknacky** [comment] 2019-03-25 11:58
Can you intercept two points below to see if the log levels are set correctly and the method is called?
* [Constructor of GoogleAdsUnaryCallLogger](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V1/GoogleAdsUnaryCallLogger.php#L55)
* [logSummary](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V1/GoogleAdsUnaryCallLogger.php#L71)

**Comment by jamiehd** [comment] 2019-03-25 12:01
The constructor is called but logSummary is not.

**Comment by jamiehd** [comment] 2019-03-25 12:03
And both the logger and logLevel are defined correctly:

/home/vagrant/Code/ad7/api/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V1/GoogleAdsUnaryCallLogger.php:58:
object(App\LoggerTest)[1033]
/home/vagrant/Code/ad7/api/vendor/googleads/google-ads-php/src/Google/Ads/GoogleAds/Lib/V1/GoogleAdsUnaryCallLogger.php:59:string 'debug' (length=5)

**Comment by fiboknacky** [comment] 2019-03-25 12:20
The only reason I can think of for now, is that your web application somehow doesn't make a call to the Google Ads API via gRPC (perhaps it's not installed in your framework, for example).

`logSummary` is called in [wait()](https://github.com/googleads/google-ads-php/blob/3612ebf21afb0bfd4947d0cfa0d7e68dfb746828/src/Google/Ads/GoogleAds/Lib/V1/GoogleAdsLoggingUnaryCall.php#L51), whose instance is created in [interceptUnaryUnary()](https://github.com/googleads/google-ads-php/blob/3612ebf21afb0bfd4947d0cfa0d7e68dfb746828/src/Google/Ads/GoogleAds/Lib/V1/GoogleAdsLoggingInterceptor.php#L60)

[That GoogleAdsLoggingInterceptor is set](https://github.com/googleads/google-ads-php/blob/3612ebf21afb0bfd4947d0cfa0d7e68dfb746828/src/Google/Ads/GoogleAds/Lib/V1/ServiceClientFactoryTrait.php#L147) only when gRPC is used as a transport protocol.

**Comment by jamiehd** [comment] 2019-03-25 13:47
Hi fibonacky,

Thanks very much for your help - you were right that grpc wasn't loaded in the php.ini used by php-fpm, so I guess it was falling back to rest and therefore not logging. I have now enabled the extention for php-fpm and it is logging correctly.

I think it would be a good idea to log rest requests as well as rpc ones though in the future. Is here a good place to request that as a feature?

Thanks

**Comment by fiboknacky** [comment] 2019-03-26 06:20
Sure. Thanks for the feedback.
I'll check with the Google API team to see if there are any concerns about that.

**Comment by fiboknacky** [comment] 2019-03-27 12:26
It looks like the support of REST logging is not trivial.
I've filed this request to the Google API team, but it'd need some non-trivial amount of time to do so.

For now, as your issue has been fixed, I'm closing this issue.

**Closed by fiboknacky** 2019-03-27 12:26 UTC
