### ISSUE TITLE
PHP 8.2 support: Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by nickbo90** [googleads/google-ads-php#870] opened 2023-01-19 07:44 UTC
**Your client library and Google Ads API versions:**
google-ads-php-v17.1.0
Google Ads API version: V12

**Your environment:**
PHP Version => 8.2.1

**Description of the bug:**
Many notices of deprecated lines.

Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated on line 152 in /composer/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php

Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated on line 152 in /composer/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php

**Steps to reproduce:**
Install php 8.2 and run a script like creating a campaign. You will get the notices

**Expected behavior:**
No notices

**Comment by fiboknacky** [comment] 2023-01-19 08:42
Thanks for reporting. That part is automatically generated, so we will need time to fix that.

**Comment by jrughani9** [comment] 2023-02-16 16:58
Your client library and Google Ads API versions:
google-ads-php-v17.1.0
Google Ads API version: V12

Your environment:
PHP Version => 8.2.1

Steps to reproduce:
Install php 8.2 and run a script like creating a campaign. You will get the notices

Expected behavior:
No notices

Description of the bug:
Many notices of deprecated lines.

```
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_client_customer is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_hidden is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_level is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_time_zone is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_test_account is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_manager is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_descriptive_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_currency_code is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_client_customer is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_hidden is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_level is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_time_zone is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_test_account is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_manager is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_descriptive_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_currency_code is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_client_customer is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_hidden is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_level is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_time_zone is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_test_account is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_manager is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_descriptive_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_currency_code is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_client_customer is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_hidden is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_level is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_time_zone is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_test_account is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_manager is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_descriptive_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_currency_code is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_client_customer is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_hidden is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_level is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_time_zone is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_test_account is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_manager is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_descriptive_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_currency_code is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_client_customer is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_hidden is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_level is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_time_zone is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_test_account is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_manager is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_descriptive_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_currency_code is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_client_customer is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_hidden is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_level is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_time_zone is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_test_account is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_manager is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_descriptive_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_currency_code is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\CustomerClient::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_tracking_url_template is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_audience_setting is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_base_campaign is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_budget is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_start_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_group is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_end_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_optimization_score is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_tracking_url_template is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_audience_setting is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_base_campaign is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_budget is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_start_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_group is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_end_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_optimization_score is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_tracking_url_template is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_audience_setting is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_base_campaign is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_budget is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_start_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_group is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_end_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_optimization_score is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_tracking_url_template is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_audience_setting is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_base_campaign is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_budget is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_start_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_group is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_end_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_optimization_score is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_tracking_url_template is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_audience_setting is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_base_campaign is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_budget is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_start_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_group is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_end_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_optimization_score is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_tracking_url_template is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_audience_setting is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_base_campaign is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_budget is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_start_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_group is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_end_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_optimization_score is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_id is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_name is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_tracking_url_template is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_audience_setting is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_base_campaign is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_budget is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_start_date is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_campaign_group is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_end_date is deprecated 
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_final_url_suffix is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_optimization_score is deprecated
Deprecated: Creation of dynamic property Google\Ads\GoogleAds\V12\Resources\Campaign::$_url_expansion_opt_out is deprecated
```

**Comment by PierrickVoulet** [comment] 2023-02-16 20:25
Looks like it's a known issue, see https://github.com/protocolbuffers/protobuf/issues/11452

**Comment by fiboknacky** [comment] 2023-03-20 17:46
Seemed the issue is fixed on https://github.com/protocolbuffers/protobuf/issues/11452

**Closed by fiboknacky** 2023-03-20 17:46 UTC
Labels: bug, triage
