### ISSUE TITLE
getting Fatal error while running getChangeDetails for change events

### ISSUE THREAD

**Issue by Vijaysinh** [googleads/google-ads-php#512] opened 2021-01-08 17:25 UTC
![error](https://user-images.githubusercontent.com/6183730/104047750-2b069600-5208-11eb-8583-1359b0ea8a7d.PNG)
I am getting api response but same time after printing API response I am getting below error.

I am using PHP.

I am using V6 api version.

Fatal error: Uncaught TypeError: Argument 1 passed to Google\Ads\GoogleAds\Util\FieldMasks::getDescriptorForMessage() must be an instance of Google\Protobuf\Internal\Message, instance of Google\Protobuf\Internal\RepeatedField given, called in C:\wamp64\www\libs\google-ads-php\src\Google\Ads\GoogleAds\Util\FieldMasks.php on line 261 and defined in C:\wamp64\www\libs\google-ads-php\src\Google\Ads\GoogleAds\Util\FieldMasks.php on line 293

**Comment by fiboknacky** [comment] 2021-01-12 07:35
Do you use the [C implementation of protobuf](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#c_implementation)? And what PHP version do you use?

**Comment by Vijaysinh** [comment] 2021-01-12 13:20
@fiboknacky I am using php 7.3.21 and I am using  PHP implementation using composer.

This is my composer.json require json,

"require": {
    "php": ">=7.2",
    "google/gax": "^1.5.0",
    "google/protobuf": "^3.14.0",
    "ulrichsg/getopt-php": "^3.4",
    "monolog/monolog": "^1.23.0 || ^2.0"
  },

**Comment by fiboknacky** [comment] 2021-01-12 13:31
BTW, what [library version](https://github.com/googleads/google-ads-php/releases) do you use and could you tell your customer ID that you use to run this example?

**Comment by Vijaysinh** [comment] 2021-01-12 14:35
@fiboknacky I am using v6 version of ads api and customerID = 1255040287

**Comment by fiboknacky** [comment] 2021-01-12 15:22
Thanks for the information.
For the version, I meant the [library version](https://github.com/googleads/google-ads-php/releases), not the Google Ads API version. Could you follow the link in the previous sentence and confirm what the library version you downloaded?

**Comment by Vijaysinh** [comment] 2021-01-12 19:38
I am using google-ads-php-v6.1.0 library version

**Comment by fiboknacky** [comment] 2021-01-15 07:16
We're looking into fixing this soon. Sorry for your inconvenience.
For now, you can just replace [this line](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Util/FieldMasks.php#L255), with `return null`.
Then, on [the first line of this method](https://github.com/googleads/google-ads-php/blob/master/examples/AccountManagement/GetChangeDetails.php#L236), add something like this:

```php
if (is_null($value)) {
  return 'none';
}
```

**Comment by Vijaysinh** [comment] 2021-01-15 11:11
@fiboknacky yes.. that I have already done for my testing purpose. I was think something is wrong in my code. 
so this you are going to consider as bug?

**Comment by fiboknacky** [comment] 2021-01-15 11:16
There is an issue in the utility method, which we're considering the best way to fix it.
There is no issue with the API server.

**Comment by Vijaysinh** [comment] 2021-01-20 21:00
I am doing same  but still I am getting errors,


( ! ) Fatal error: Uncaught TypeError: Argument 1 passed to Google\Ads\GoogleAds\Util\FieldMasks::getDescriptorForMessage() must be an instance of Google\Protobuf\Internal\Message, instance of Google\Protobuf\Internal\RepeatedField given, called in C:\wamp64\www\libs\google-ads-php\src\Google\Ads\GoogleAds\Util\FieldMasks.php on line 262 and defined in C:\wamp64\www\libs\google-ads-php\src\Google\Ads\GoogleAds\Util\FieldMasks.php on line 294
--

**Comment by fiboknacky** [comment] 2021-01-21 04:35
Could you share what's in the FieldMasks.php file of yours on lines 262 and 294?

**Comment by Vijaysinh** [comment] 2021-01-21 08:36
@fiboknacky please see this full condition
if ($fieldDescriptor->getType() === GPBType::MESSAGE) {
                    $object = $fieldValue;
                    if (is_null($object)) {
                        return null;
                        // throw new UnexpectedValueException(
                        //     'The object to get its field value is null. '
                        //     . 'This could happen when the passed field mask path points to the '
                        //     . ' wrong place, where the nested message is not set.'
                        // );
                    }
                    $descriptor = self::getDescriptorForMessage($fieldValue);
                }

**Comment by Vijaysinh** [comment] 2021-01-21 08:38
@fiboknacky here the full file you can check.

https://gist.github.com/Vijaysinh/028cce3e826a53bed922c18f3e2dd267#file-fieldmasks-php

**Comment by fiboknacky** [comment] 2021-01-21 11:24
Do you test against the same customer ID you mentioned above?

**Comment by Vijaysinh** [comment] 2021-01-22 00:26
@fiboknacky Yes, same customer ID.

**Comment by fiboknacky** [comment] 2021-01-28 06:26
I cannot reproduce your error, but I do see the place we can improve.
We're working on it in #519. It's not finished yet, but feel free to copy the code to your program and try by yourself too.

**Comment by fiboknacky** [comment] 2021-02-15 06:47
Update: We cannot reproduce the error you mentioned, i.e., the field path returned as a repeated field. If the API returns a repeated field, it might be a bug on the API side.
I'll close this issue for now, but feel free to re-open this if you have more detailed information like what the returned field path string looks like.
You may manually edit the code to print the returned field path string before the exception is thrown.

**Closed by fiboknacky** 2021-02-15 06:47 UTC
Labels: bug
