### ISSUE TITLE
change_event query returns Internal error encountered, code - 13

### ISSUE THREAD

**Issue by Luke-sudo1** [googleads/google-ads-php#467] opened 2020-11-21 13:56 UTC
Greetings,

My setup is :
google-ads-php: v6.0
php: v7.4.12
server: localhost wamp apache 2.4.33 

I am using AWQL query to get change_event details as provided in this example: 
google-ads-php/examples/AccountManagement/GetChangeDetails.php 

`$query = "SELECT "
                . "change_event.resource_name, "
                . "change_event.change_date_time, "
                . "change_event.change_resource_name, "
                . "change_event.user_email, "
                . "change_event.client_type, "
                . "change_event.change_resource_type, "
                . "change_event.old_resource, "
                . "change_event.new_resource, "
                . "change_event.resource_change_operation, "
                . "change_event.changed_fields "
                . "FROM change_event "
                . sprintf(
                    "WHERE change_event.change_date_time <= %s ",
                    date_format(new DateTime("-1 days"), "Ymd")
                    )
                . sprintf(
                    "AND change_event.change_date_time >= %s ",
                    date_format(new DateTime("-20 days"), "Ymd")
                    )
                . "ORDER BY change_event.change_date_time DESC "
                . "LIMIT 100";
`

Then I proceed with search method

`$response = $googleAdsServiceClient->search($customerId, $query,  ['pageSize' => 100]);`

How ever it crashes with only this exception: 
{ "message": "Internal error encountered.", "code": 13, "status": "INTERNAL", "details": [] } and no more details.

And stack trace looks like this:
\vendor\google\gax\src\ApiException.php
Google\ApiCore\ApiException :139
Google\ApiCore\ApiException :109

\vendor\google\gax\src\Transport\RestTransport.php
Google\ApiCore\Transport\RestTransport :165
Google\ApiCore\Transport\RestTransport :131
GuzzleHttp\Promise\Promise :204
GuzzleHttp\Promise\Promise :153
GuzzleHttp\Promise\TaskQueue :48
GuzzleHttp\Promise\Promise :248
GuzzleHttp\Promise\Promise :224
GuzzleHttp\Promise\Promise :269
GuzzleHttp\Promise\Promise :226
GuzzleHttp\Promise\Promise :62
Google\Ads\GoogleAds\V6\Services\Gapic\GoogleAdsServiceGapicClient :641
Google\Ads\GoogleAds\V6\Services\Gapic\GoogleAdsServiceGapicClient :285

If there are no change records in the account it returns an empty array.

if I remove these four lines from query :
. "change_event.old_resource, "
. "change_event.new_resource, "
. "change_event.resource_change_operation, "
. "change_event.changed_fields "

It returns data correctly (without these fields, of course).

The service client is authenticated correctly, because before this query I run different query for metrics and it works fine.

Maybe you could help me find out why this issue occurs ?

Thanks a lot

**Comment by mrpavlikov** [comment] 2020-11-23 12:53
Running into exactly same issue with REST transport. Even simple query like this does not work:

```
SELECT change_event.resource_name FROM change_event WHERE change_event.change_date_time DURING LAST_14_DAYS LIMIT 5
```

**Comment by PierrickVoulet** [comment] 2020-11-23 13:46
Hi @Luke-sudo1 and @mrpavlikov - I could not reproduce any of your errors on my side neither with the REST transport nor with the gRPC transport. Both errors are likely related to issues with the Google Ads API, not the client library, please contact their [dedicated support](https://developers.google.com/google-ads/api/support?hl=en) to continue the investigation.

I am closing this issue but feel free to comment if any follow up is needed for the client library.

**Closed by PierrickVoulet** 2020-11-23 13:46 UTC
Labels: bug

**Comment by mrpavlikov** [comment] 2020-12-01 14:57
Long story short: indeed it is an API failure, happens on ad level, still no fix on live servers tho. 

https://groups.google.com/g/adwords-api/c/4wDgGRa0lFA/m/IcCOijGJAgAJ
