### ISSUE TITLE
Memory leak in result object create adgroup

### ISSUE THREAD

**Issue by cappadaan** [googleads/google-ads-php#579] opened 2021-04-29 08:34 UTC
- v8.1.0
-  PHP 8.0.3

- Code example 

$oAuth2Credential = (new OAuth2TokenBuilder())
			->withClientId(GOOGLE_ADS_API_CLIENT_ID)
			->withClientSecret(GOOGLE_ADS_API_CLIENT_SECRET)
			->withRefreshToken(GOOGLE_ADS_API_REFRESH_TOKEN)
			->build();

$oGoogleAdsClient = (new GoogleAdsClientBuilder())
    ->withOAuth2Credential($oAuth2Credential)
    ->withDeveloperToken(GOOGLE_ADS_API_DEVELOPER_TOKEN)
    ->withLoginCustomerId(GOOGLE_ADS_API_MANAGER_ID)
    ->withTransport('rest')
    ->build();

$sCampaignResourceName = ResourceNames::forCampaign(GOOGLE_ADS_API_CUSTOMER_ID, GOOGLE_ADS_CAMPAIGN_ID_CITIES);

$aOperations = [];

$oAdGroup = new AdGroup([
    'name' => $sAdGroupName,
    'campaign' => $sCampaignResourceName,
    'status' => AdGroupStatus::ENABLED,
    'type' => AdGroupType::SEARCH_STANDARD,
    'cpc_bid_micros' => 50000000
]);

$oAdGroupOperation = new AdGroupOperation();
$oAdGroupOperation->setCreate($oAdGroup);
$aOperations[] = $oAdGroupOperation;

// Issues a mutate request to add the ad groups.
$adGroupServiceClient = self::$oGoogleAdsClient->getAdGroupServiceClient();
$oResponse = $adGroupServiceClient->mutateAdGroups(
    GOOGLE_ADS_API_CUSTOMER_ID,
    $aOperations
);

print_r($oResponse); 

This print_r causes a huge memory consumption.

PHP Fatal error:  Allowed memory size of 9663676416 bytes exhausted (tried to allocate 6440357888 bytes)

**Comment by fiboknacky** [comment] 2021-05-07 11:08
This is probably a duplicate of #575. Please follow there.

**Closed by fiboknacky** 2021-05-07 11:08 UTC
Labels: bug, duplicate
