### ISSUE TITLE
Trait method getGrpcDependencyStatus has not been applied

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#684] opened 2021-11-26 12:07 UTC
Hi,

I am getting error which suggest

PHP Fatal error:  Trait method getGrpcDependencyStatus has not been applied, because there are collisions with other trait methods on Google\Ads\GoogleAds\Lib\V8\GoogleAdsClient in google-ads-php/src/Google/Ads/GoogleAds/Lib/V8/GoogleAdsClient.php on line 27

Thanks,

**Comment by PierrickVoulet** [comment] 2021-11-26 13:06
Hi @chiragvels - Thank you for reporting this issue. Could you provide the following information so that we can investigate?

**Your client library version:**

> This should be a released version, see https://github.com/googleads/google-ads-php/releases.

**Your environment:**

> You can paste the output generated by our complementary script: https://github.com/googleads/google-ads-php/blob/master/scripts/print_php_information.php.
>
>Alternatively, please provide with the following pieces of information:
>
> * The PHP version: Run `php -v`.
> * The name and version of the operating system: Run `php -r 'print php_uname();'`.
> * Whether the PHP Extension `protobuf` is used or not: Run `php -r 'print phpversion("protobuf");'`.
> * Whether the PHP Extension `grpc` is used or not: Run `php -r 'print phpversion("grpc");'`.
> * The type of transport being used (`grpc` or `rest`): See https://developers.google.com/google-ads/api/docs/client-libs/php/transport.

**The steps to reproduce:**

> The best is to provide an example of code that illustrates the bug.

**Comment by chiragvels** [comment] 2021-11-27 16:06
Hi,

Your client library version:
google-ads-php-v12.1.0

PHP Version => 7.4.14
System => Linux 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64

The PHP Extension grpc is installed: 1.33.1
The PHP Extension protobuf is installed: 3.19.1
Trasport used: grpc


The steps to reproduce:
I have just switched my branch from master to main by doing this
git pull --all
git fetch && git checkout main

On master I have google-ads-php-v11.0.0 and after switching to main client library version:google-ads-php-v12.1.0

Code I am using:
```
$googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
$query = "SELECT
                    ad_group_criterion.criterion_id,
                    ad_group_criterion.keyword.text,
                    ad_group_criterion.keyword.match_type,
                    ad_group_criterion.status,
                    campaign.id,
                    campaign.name,
                    campaign.status,
                    ad_group.id,
                    ad_group.name,
                    ad_group.status,
                    segments.date,
                    metrics.average_cpc,
                    metrics.clicks,
                    metrics.conversions,
                    metrics.conversions_from_interactions_rate,
                    metrics.cost_micros,
                    metrics.cost_per_conversion,
                    metrics.ctr,
                    metrics.impressions,
                    metrics.view_through_conversions,
                    metrics.absolute_top_impression_percentage,
                    metrics.top_impression_percentage
                FROM
                    keyword_view
                WHERE
                    campaign.status IN ('ENABLED', 'PAUSED')
                    AND ad_group.status IN ('ENABLED')
                    AND ad_group_criterion.status IN ('ENABLED')
                    AND segments.date >= {$startDate} AND segments.date <= {$endDate}";
$response = $googleAdsServiceClient->search($customerId, $query, $options);

```
Thanks

**Comment by PierrickVoulet** [comment] 2021-11-30 16:09
@chiragvels #690 should fix this when merged. Feel free to give it a try and let us know if it does not help.

**Closed** 2021-11-30 18:55 UTC
Labels: bug

**Comment by chiragvels** [comment] 2021-12-01 05:52
Hi @PierrickVoulet ,

Ok, I will try again once I get time this week.

Thanks,

**Comment by chiragvels** [comment] 2021-12-03 07:47
Hi @PierrickVoulet ,

This will generate warnings in 

A PHP Error was encountered

Severity:    Warning
Message:     array_push() expects at least 2 parameters, 1 given
Filename:   google-ads-php/src/Google/Ads/GoogleAds/Lib/V8/ServiceClientFactoryTrait.php
Line Number: 235


Thanks

**Comment by PierrickVoulet** [comment] 2021-12-03 14:43
> Severity: Warning Message: array_push() expects at least 2 parameters, 1 given Filename: google-ads-php/src/Google/Ads/GoogleAds/Lib/V8/ServiceClientFactoryTrait.php Line Number: 235

Are you still using PHP `7.4`? Based on [PHP's documentation](https://www.php.net/manual/en/function.array-push.php), the second parameter of `array_push` is optional since the version `7.3.0` of PHP (which is the minimal version of PHP we currently support).

**Comment by chiragvels** [comment] 2021-12-03 16:54
HI @PierrickVoulet ,

It is indeed the issue.
PHP version reported by phpinfo() and php -v (in the CLI) are both different.

I will check with team and let you know if still has an issue.

Thanks,
