### ISSUE TITLE
Error Customer Id Login

### ISSUE THREAD

**Issue by adrianlaraperez88** [googleads/google-ads-php#91] opened 2019-05-23 15:10 UTC
Hi Team,

I have a problem, now working with the new version for Google Ads but I have this error.

` Grpc\Timeval::__construct() expects parameter 1 to be integer, float given in C:\xampp\htdocs\google_ads_new_version\google-ads-php\vendor\grpc\grpc\src\lib\AbstractCall.php on line 55

Warning: Grpc\Timeval::__construct() expects parameter 1 to be integer, float given in C:\xampp\htdocs\google_ads_new_version\google-ads-php\vendor\grpc\grpc\src\lib\AbstractCall.php on line 55
PHP Fatal error: Uncaught InvalidArgumentException: Timeval expects a long in C:\xampp\htdocs\google_ads_new_version\google-ads-php\vendor\grpc\grpc\src\lib\AbstractCall.php:55`

CUSTOMER_ID = '629-195-0585';

$response =
$googleAdsServiceClient->search($customerId, $query, ['pageSize' => self::PAGE_SIZE]);

Note: This Customer Id working in the old version in production.

**Comment by fiboknacky** [comment] 2019-05-23 15:23
Have you removed hyphens before passing to the method?

**Comment by adrianlaraperez88** [comment] 2019-05-23 15:30
Yes. const CUSTOMER_ID = '1206260014';

**Comment by fiboknacky** [comment] 2019-05-23 15:35
Looks like it's a duplicate of [this issue](https://github.com/googleads/google-ads-php/issues/70). Could you please use 64-bit PHP instead?

**Comment by adrianlaraperez88** [comment] 2019-05-23 15:50
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_grpc.dll' (tried: C:\xampp\php\ext\php_grpc.dll (%1 is not a valid Win32 application.), C:\xampp\php\ext\php_php_grpc.dll.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'php_grpc.dll' (tried: C:\xampp\php\ext\php_grpc.dll (%1 is not a valid Win32 application.), C:\xampp\php\ext\php_php_grpc.dll.dll (The specified module could not be found.)) in Unknown on line 0

**Comment by fiboknacky** [comment] 2019-05-23 15:52
I'm not sure what steps you have done too. Any details would be appreciated.

**Comment by adrianlaraperez88** [comment] 2019-05-23 15:55
Only change gRpc 32 bit to 64 bit. Now show this error, let me try to update Xampp to 64 bit, this not my environment

**Comment by adrianlaraperez88** [comment] 2019-05-23 16:01
This customer Id working fine in version googleads_v201809.

ApiException was thrown with message '{
    "message": "The caller does not have permission",
    "code": 7,
    "status": "PERMISSION_DENIED",
    "details": [
        {
            "@type": 0,
            "data": "type.googleapis.com\/google.ads.googleads.v1.errors.GoogleAdsFailure"
        },
        {
            "@type": 0,
            "data": [
                {
                    "errorCode": {
                        "authorizationError": "USER_PERMISSION_DENIED"
                    },
                    "message": "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https:\/\/developers.google.com\/google-ads\/api\/docs\/concepts\/call-structure#login-customer-id"
                }
            ]
        }
    ]
}'.

**Comment by fiboknacky** [comment] 2019-05-23 16:25
As hinted in the error message, have you passed the [login-customer-id header](https://developers.google.com/google-ads/api/docs/concepts/call-structure#login-customer-id)?

**Comment by adrianlaraperez88** [comment] 2019-05-23 16:33
I have many Account, I need management in the code, not in the config file. My Code in the old version.

` $customerIds = explode(",",$config_settings["costumerId"]);
                foreach ($customerIds  as $customerId) {
                   $session = (new AdWordsSessionBuilder())
                    ->fromFile($config)
                    ->withOAuth2Credential($oAuth2Credential)
                    ->withClientCustomerId($customerId)
                    ->build();
}`

**Comment by fiboknacky** [comment] 2019-05-23 16:46
That's totally fine.

However, the login-customer-id header is necessary, so you need to provide it.
You can use [this function](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/Lib/V1/GoogleAdsClientBuilder.php#L118) to provide it programmatically instead.

**Comment by adrianlaraperez88** [comment] 2019-05-23 17:04
I try before with this function but i have same error:

`    $googleAdsClient = (new GoogleAdsClientBuilder())
            ->fromFile()
            ->withOAuth2Credential($oAuth2Credential)
            ->withLoginCustomerId('1206260014')
            ->build();`

**Comment by fiboknacky** [comment] 2019-05-24 00:21
Then, probably you put in the wrong login customer ID. :)
Could you tell me what the customer ID you try to access, when you pass 1206260014 as a login customer ID?

**Comment by adrianlaraperez88** [comment] 2019-05-24 15:18
I do not understand your question well, I have my file ini, and I have my client. Does that need more?

`ClientId:
1206260014

Ini file:
[GOOGLE_ADS]
developerToken = "XXXXXXXX"


[OAUTH2]
; For installed application or web application flow.
clientId = "XXXXX-XXXXXX.apps.googleusercontent.com"
clientSecret = "XXXXXXXXXXXXXXXXX"
refreshToken = "XXXXXXXXXX"`

**Comment by adrianlaraperez88** [comment] 2019-05-24 16:02
Hi, @fiboknacky thank for you help you right for this version need another ClientId and accept new API Conditions.

![image](https://user-images.githubusercontent.com/19626181/58341231-2408f500-7e24-11e9-8419-f81b377ba279.png)


Thank you.

**Comment by fiboknacky** [comment] 2019-05-24 16:29
Could you confirm the guide I mentioned in [this reply](https://github.com/googleads/google-ads-php/issues/91#issuecomment-495289629)?
May I ask if you realize that we now need a "login customer ID header" (it's _not_ the same as "customer ID"), if you use a refresh token of a manager account?

**Comment by adrianlaraperez88** [comment] 2019-05-24 16:49
You right the problem in old Version no need the parent account only the subaccounts, now i need put in config file  login-customer-id.

**Comment by fiboknacky** [comment] 2019-05-24 16:56
Yes, can you fix your problem now?

**Comment by adrianlaraperez88** [comment] 2019-05-24 16:57
Yes.Thank you.

**Closed** 2019-05-24 19:48 UTC
