### ISSUE TITLE
Error getting data metrics

### ISSUE THREAD

**Issue by miguelgracia** [googleads/google-ads-php#161] opened 2019-07-18 11:36 UTC
I am trying to execute a metric query, but the library returns the following error:

> In Message.php line 1687:
>   Call to a member function jsonByteSize() on float  

The query is the following

```
SELECT campaign.id,campaign.name,ad_group.id,ad_group.name,
ad_group_criterion.criterion_id, ad_group_criterion.keyword.text, ad_group_criterion.keyword.match_type, metrics.clicks,
metrics.cost_micros,metrics.impressions, metrics.conversions,
metrics.average_cpc,metrics.ctr 
FROM keyword_view 
WHERE segments.date DURING YESTERDAY AND campaign.id=xxxxx
```

Thanks for your help

**Comment by fiboknacky** [comment] 2019-07-18 15:10
@PierrickVoulet  Would this be related to the C implementation?

**Comment by PierrickVoulet** [comment] 2019-07-19 22:20
Hi,

@fiboknacky: actually this seems related to the Protobuf.

@miguelgracia I need your help to continue the investigation:
- Could you run the command `php -i | grep protobuf` and let me know the output?
- Could you provide the minimum script to reproduce this issue?

Thanks,

**Comment by fiboknacky** [comment] 2019-07-20 02:12
And what client library version are you using?

**Comment by miguelgracia** [comment] 2019-07-22 11:55
@fiboknacky. I was using V1 of the library. With V2 it works.

@PierrickVoulet This is the script to reproduce the error

[GoogleMetricsIssue.zip](https://github.com/googleads/google-ads-php/files/3417181/GoogleMetricsIssue.zip)

Just add the configuration parameters in the .ini file and in the file Metric.php

I hope this helps

**Comment by PierrickVoulet** [comment] 2019-07-22 13:14
Thanks @miguelgracia, I reproduce the error on my side using GoogleAdsClientBuilder V1 and the PHP implementation of Protobuf **only**:

```
PHP Fatal error:  Uncaught Error: Call to a member function jsonByteSize() on float in /usr/local/google/home/pierrick/git/gh/fork/ga/google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:1687
Stack trace:
#0 /usr/local/google/home/pierrick/git/gh/fork/ga/google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1828): Google\Protobuf\Internal\Message->fieldDataOnlyJsonByteSize(Object(Google\Protobuf\Internal\FieldDescriptor), 0)
#1 /usr/local/google/home/pierrick/git/gh/fork/ga/google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1936): Google\Protobuf\Internal\Message->fieldJsonByteSize(Object(Google\Protobuf\Internal\FieldDescriptor))
#2 /usr/local/google/home/pierrick/git/gh/fork/ga/google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1687): Google\Protobuf\Internal\Message->jsonByteSize()
#3 /usr/local/google/home/pierrick/git/gh/fork/ga/google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1828): Goo in /usr/local/google/home/pierrick/git/gh/fork/ga/google-ads-php/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php on line 1687
```

The error disappears if either I change to use V2 service or I change to use the C implementation of Protobuf.

The error looks similar to the issue #104 which was supposed to be fixed with V2 but never verified.

@miguelgracia because V2 fixes the issue, do you have the possibility to upgrade to this version?

**Comment by miguelgracia** [comment] 2019-07-23 06:05
Yes, no problem @PierrickVoulet, I have already migrated to v2.

Thanks!

**Closed** 2019-07-23 06:05 UTC
