### ISSUE TITLE
Missing request Id when we upload offline conversions

### ISSUE THREAD

**Issue by rilwanfit** [googleads/google-ads-php#1005] opened 2024-04-02 09:34 UTC
**Your question:**
We are currently migrating our project from Google Ads API V15 to V16 with the release of Google Ads PHP 22.1.0.

In our application, we used to log the `RequestID` whenever we sent offline conversions to Google Ads API. (both success calls as well as failed calls)

We used the following code when we used V15.

```
use Google\Ads\GoogleAds\V15\Services\ConversionUploadServiceClient;

 /** @var UploadClickConversionsResponse $response */
[$response,$status] = $conversionUploadService->uploadClickConversions( 
    $customerId,
    $conversions,
    true,
    ['withResponseMetadata' => true],
);
```
The `$status` is the `GoogleAdsResponseMetadata` where we can get the request-id.

## Problem
With V16 the above code is NOT working anymore. So we have updated the code to the following
```
use Google\Ads\GoogleAds\V16\Services\Client\ConversionUploadServiceClient;

$response = $conversionUploadService->uploadClickConversions(
        UploadClickConversionsRequest::build($customerId, $conversions, true),
 );
```
With this code, we missed the entire `GoogleAdsResponseMetadata` object. 

How can we get the request Id with new version (V16)? (both success calls as well as failed calls)

**Comment by fiboknacky** [comment] 2024-04-02 11:25
It may be related to the change of new generated code and gax-php. Let me ask the owners of the repository and get back here.

**Comment by fiboknacky** [comment] 2024-04-02 11:27
BTW, what [google/gax](https://github.com/googleapis/gax-php) did you install in your project?

**Comment by rilwanfit** [comment] 2024-04-02 11:38
We don't use [google/gax](https://github.com/googleapis/gax-php). We are using  "googleads/google-ads-php": "^v22.1.0"

**Comment by bshaffer** [comment] 2024-04-09 14:51
Without looking too deeply (I'm not at a laptop), the first example contains `['withResponseMetadata' => true]` and the second does not. Have you tried removing this line?

**Comment by bshaffer** [comment] 2024-04-09 14:52
Hmm, after a second thought, I think the issue is that the API has changed, and the second way you have is the new (and correct) way to make the API call, which would mean this is working as designed.

**Comment by fiboknacky** [comment] 2024-04-10 07:16
I don't think so. The API specification itself hasn't changed.

We have [`GoogleAdsGapicTrait`](https://github.com/googleads/google-ads-php/blob/73ab3a3d6ddab3bac2b28da92f0da3220ba4f432/src/Google/Ads/GoogleAds/Lib/V14/GoogleAdsGapicClientTrait.php) that has been used for a long time with the GAPIC v1 classes.

[`modifyUnaryCallable`](https://github.com/googleads/google-ads-php/blob/73ab3a3d6ddab3bac2b28da92f0da3220ba4f432/src/Google/Ads/GoogleAds/Lib/V14/GoogleAdsGapicClientTrait.php#L102) and [`modifyStreamingCallable`](https://github.com/googleads/google-ads-php/blob/73ab3a3d6ddab3bac2b28da92f0da3220ba4f432/src/Google/Ads/GoogleAds/Lib/V14/GoogleAdsGapicClientTrait.php#L116) are the methods heavily used to inject what we need such as GoogleAdsException and to return the metadata like shown above.

The GAPIC v1 classes can call these functions successfully, but somehow for GAPIC v2 classes (like [GoogleAdsServiceClient](https://github.com/googleads/google-ads-php/blob/73ab3a3d6ddab3bac2b28da92f0da3220ba4f432/src/Google/Ads/GoogleAds/V15/Services/Client/GoogleAdsServiceClient.php#L60-L63)), it looks like there is something changed underneath that makes [the result of a callable](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/Lib/V14/UnaryGoogleAdsResponseMetadataCallable.php#L45) not propagated back.

Has anything in `gax-php` changed that would affect how the middleware works for this specific case?

**Comment by bshaffer** [comment] 2024-04-22 21:59
@fiboknacky  If I could get a repro test going for this, we could roll back versions of GAX until we land on a version where it works - this would go a long way in helping diagnose this issue

**Comment by fiboknacky** [comment] 2024-04-30 11:01
FYI @rilwanfit 

Brent (@bshaffer) and I synced offline and we found the root cause.
Brent has implemented a new solution (#1013), which was merged last week.
I'll release a new client library version soon this week at earliest.

**Comment by fiboknacky** [comment] 2024-05-31 08:24
[New version of the client library](https://github.com/googleads/google-ads-php/releases/tag/v23.0.1) was released.

**Closed by fiboknacky** 2024-05-31 08:24 UTC
Labels: question, triage

**Comment by dabontv** [comment] 2024-07-03 02:07
Is there an example to get metadata in the new update? It seems the api docs are still outdated https://developers.google.com/google-ads/api/docs/client-libs/php/response-metadata

**Comment by fiboknacky** [comment] 2024-07-03 09:43
We've just updated the doc. Sorry for your inconvenience.

**Comment by dabontv** [comment] 2024-07-03 15:17
Using v17 example: 
```
        $conversionUploadServiceClient = $googleAdsClient->getConversionUploadServiceClient();
        $response = $conversionUploadServiceClient->uploadClickConversions(
            UploadClickConversionsRequest::build($customerId, $clickConversion, true),
            ['withResponseMetadata' => true]
        );
```

$conversionUploadServiceClient->getResponseMetadata(); will return null

**Comment by fiboknacky** [comment] 2024-07-03 15:56
I cannot reproduce your issue. It works as expected on my machine.
Could you share the whole code? And what's the result? Can you still get your log and request ID in there?

**Comment by ujwaldhakal** [comment] 2024-10-03 12:13
@dabontv I am still stuck around this issue,  were you able to find a workaround?

**Comment by dabontv** [comment] 2024-10-03 12:19
> @dabontv I am still stuck around this issue, were you able to find a workaround?

We set up our own logs (https://developers.google.com/google-ads/api/docs/client-libs/php/logging)

**Comment by ujwaldhakal** [comment] 2024-10-03 12:24
> https://developers.google.com/google-ads/api/docs/client-libs/php/logging

Thanks for reply.  
Using the logs would require additional changes to map each conversion with the request ID. 
Now for me, the only option is to wait for this thing to work as previously.  We already built around something that could map each conversion with a request ID. 
Let's see what @fiboknacky  has to say on this :)
