### ISSUE TITLE
Guide mentions non-existing AuthenticateInDesktopApplication.php file

### ISSUE THREAD

**Issue by Ravizaum** [googleads/google-ads-php#794] opened 2022-05-05 01:27 UTC
The Getting Started guide mentions the use of a file that does not exist in the library as of right now:

Run the [AuthenticateInDesktopApplication](https://github.com/googleads/google-ads-php/blob/master/examples/Authentication/AuthenticateInDesktopApplication.php) example, which will prompt you for your OAuth2 client ID and secret.

The file AuthenticateInDesktopApplication.php does not exist in this repo anymore. Please update the guide accordingly.

**Comment by PierrickVoulet** [comment] 2022-05-05 13:26
Thank you for reporting this! I sent #796 to fix this, please take a look.

**Comment by Ravizaum** [comment] 2022-05-05 13:37
Appreciate it. I've looked into it, but I appear to be having difficulties with this approach, or perhaps it's a bug. 

After using the generated link to login in a browser and authorize the app, the redirect to 127 (localhost I think) displays a generic chrome error page. Is this supposed to be ran on prod. in a hosted server? Because it makes no sense for me to go to a localhost address in my browser, if the temporary localhost is supposedly being ran on my server.

**Comment by angelbt91** [comment] 2022-05-05 16:22
Hi @Ravizaum! Is a "Page not found" error message what you are seeing, by any chance?

**Comment by PierrickVoulet** [comment] 2022-05-05 16:57
@Ravizaum Did you have the chance to follow this [guide](https://developers.google.com/google-ads/api/docs/oauth/cloud-project)? For local testing that's compatible with the default configuration in our client library examples, you need to add `http://127.0.0.1` as an authorized redirect URI of your Google API Console Project.

**Comment by Ravizaum** [comment] 2022-05-05 18:38
> Hi @Ravizaum! Is a "Page not found" error message what you are seeing, by any chance?
I believe so! @angelbt91 

> @Ravizaum Did you have the chance to follow this [guide](https://developers.google.com/google-ads/api/docs/oauth/cloud-project)? 
Yes! That's the one I followed.

> For local testing that's compatible with the default configuration in our client library examples, you need to add `http://127.0.0.1` as an authorized 
My app type is desktop. Additionally, what do you mean with local testing? I'm trying to run this on production.

Thanks XD

**Comment by angelbt91** [comment] 2022-05-05 18:43
So @Ravizaum I was struggling today just with that. My app type is also desktop, so I couldn't find any place to find a redirect uri field to fill (though the guide says that there should be one).

I found a workaround to avoid that "Page not found" problem: I just commented out the check that makes this response appear on the [GenerateUserCredentials](https://github.com/googleads/google-ads-php/blob/HEAD/examples/Authentication/GenerateUserCredentials.php) file. That is, I commented / deleted lines 114 to 123. Not elegant, but it worked. Hope it helps!

**Comment by Ravizaum** [comment] 2022-05-05 18:45
@angelbt91 are we talking about the same auth page? For me it was to get a refresh token, assuming that's you too, do the tokens just appear in the command line?

**Comment by angelbt91** [comment] 2022-05-05 18:51
@Ravizaum yes, I was also trying to retrieve the refresh token following the desktop app oAuth flow. Before commenting out those lines, I was getting a "Page nout found" message after giving permissions through my Gmail account. After commenting out those lines, I got in my browser a message saying something like "Check your console, your refresh token is there" and yeah, it was there.

**Comment by Ravizaum** [comment] 2022-05-05 18:54
Awesome! I'll give this a try. Thank you so much.
@PierrickVoulet any light on why we are getting that "Page not found"?

**Comment by PierrickVoulet** [comment] 2022-05-05 19:11
> @PierrickVoulet any light on why we are getting that "Page not found"?

@fiboknacky I know you recently worked with this code example, any insight you could provide?

**Comment by Ravizaum** [comment] 2022-05-06 01:35
@angelbt91 just tried it, but no luck. But first, let me tell you why I think that is.

Yesterday after many unsuccesful attempts with the [GenerateUserCredentials](https://github.com/googleads/google-ads-php/blob/HEAD/examples/Authentication/GenerateUserCredentials.php) file, I started to look for alternative ways to get a refresh token, until I found one guy **who used the [OAuth Playground](https://developers.google.com/oauthplayground/) with his real app credentials to generate a refresh token**. I did that and it worked 100%.

Now, I just tried your idea, but it didnt work, I kept getting redirected to the same 127 error page, **but this time, right after logging in the account (before, I managed to get to the authorize screen)**. I wondered if it was because of the lines I commented out as of your suggestion. I uncommented them, and the same thing happened: not even got to the authorize screen.

Another thing, the error screen is not a 404, but a:

> This site can’t be reached127.0.0.1 refused to connect.
>   Try:
>   
>   Checking the connection
>   [Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
>   ERR_CONNECTION_REFUSED

And this refreshed my memory, **the error I got in the first place yesterday was not a 404**, but a ERR_CONNECTION_REFUSED

So now I wonder if I this is all happening because I already have a refresh token (the one I got with the Playground). I understand that the way I got it is not the ideal, so I suspect i'd have to revoke that one, then try your method. I'm just afraid of it not working and I end up losing the refresh token I do have. That's all assuming I can revoke that one. 

Additionally, @PierrickVoulet , the playground provides a very criptic message about Refresh Tokens generated there expiring after 24 hours, but it is unclear wether this happens to Tokens that use fake Playground credentials only, or to ones with real creds too. **Can you confirm that for me? Is my Token good?**

**Comment by Ravizaum** [comment] 2022-05-06 01:39
Ah, @PierrickVoulet could you please briefly explain this to me? Thanks!

> I created the project in GCP as desktop type. So I believe I can't specify the redirect URI
> Additionally, what do you mean with local testing? I'm trying to run this on production.

It still makes zero sense to me, about spinning up a temp server in my host (i'm on prod., hosted on GCP), and trying to access it with a localhost URL from my personal computer's browser. Perhaps a tunnel is necessary?

**Comment by PierrickVoulet** [comment] 2022-05-06 12:11
@Ravizaum Refresh tokens are designed to remain valid for much longer than 24 hours (see [OAuth documentation](https://developers.google.com/identity/protocols/oauth2#5.-refresh-the-access-token,-if-necessary.)). I think you confused it with **access token** which [always expire by design](https://developers.google.com/identity/protocols/oauth2#4.-send-the-access-token-to-an-api.)?

We just published an updated version of our [guides](https://developers.google.com/google-ads/api/docs/client-libs/php/oauth-web) for the desktop and web flows, could you try it again? In our code example, we starts a tiny server on `127.0.0.1` on a random port (used for the loopback as recommended by [OAuth documentation](https://developers.google.com/identity/protocols/oauth2/native-app#redirect-uri_loopback)), do you have any configuration on your environment that could make it fail?

**Comment by Ravizaum** [comment] 2022-05-06 13:14
@PierrickVoulet, I'm running a default Bitnami Wordpress instance on GCP. I don't really see any configuration that could conflict with this server. I'll try to look this up tho.

Also, about the refresh expiry, this is what I was refereing to on the Playground. In the left side panel, in step two at the bottom of the panel, there is this message:

> Note: The OAuth Playground will automatically **revoke refresh tokens** after 24h. You can avoid this by specifying your own application OAuth credentials using the Configuration panel.

Also, is it possible for me to revoke my own refresh token?

**Comment by PierrickVoulet** [comment] 2022-05-06 13:28
Thanks for clarifying. [Here](https://developers.google.com/identity/protocols/oauth2?hl=en#expiration) is the documentation I could find about refresh token expiration (including [revoke](https://support.google.com/accounts/answer/3466521#remove-access)). I hope it helps.

**Comment by fiboknacky** [comment] 2022-05-06 14:11
@Ravizaum @angelbt91 

The example itself spins up a tiny server, so what about you run this locally instead of on a host?
It should work for both OAuth desktop and web apps. (For desktop apps, we don't need to specify a redirect URI).
I know that it wouldn't be super convenient in your case, but we usually don't fetch refresh tokens very often.

**Comment by Ravizaum** [comment] 2022-05-10 17:57
> The example itself spins up a tiny server, so what about you run this locally instead of on a host?

@fiboknacky will give it a try! Is this method specifically intended to be run locally?

**Comment by fiboknacky** [comment] 2022-05-11 05:53
Yes, the example itself is supposed to be run locally, since we don't expect that we need to use it very often. :)
In addition, it serves as an example, so in case you need to make it fit to your applications, you'd need to copy and modify it.

**Comment by Ravizaum** [comment] 2022-05-12 13:22
@fiboknacky I see, thanks! Do I need to revoke my previous refresh token in order to generate a new one with this method?

> the example itself is supposed to be run locally

Shouldn't this be explicitly stated on the documentation? I think it would be a great idea, and would avoid future issues like this.

**Comment by fiboknacky** [comment] 2022-05-12 14:04
No, you don't need to revoke your previous refresh token in order to generate a new one.

**Comment by Ravizaum** [comment] 2022-05-18 21:17
Hey! 
What about this?


> @fiboknacky I see, thanks! Do I need to revoke my previous refresh token in order to generate a new one with this method?
> 
> > the example itself is supposed to be run locally
> 
> Shouldn't this be explicitly stated on the documentation? I think it would be a great idea, and would avoid future issues like this.


I think that's pretty much it, then we can close this issue.

**Comment by fiboknacky** [comment] 2022-05-20 07:48
Thanks for the suggestion but I have no bandwidth for doing this yet. 
I'll close this once it's done.

**Closed** 2022-07-06 12:32 UTC
Labels: bug

**Comment by RoyBellingan** [comment] 2022-11-28 17:27
Documentation still point to the non existent file https://github.com/googleads/google-ads-php/wiki/OAuth-Installed-Application-Flow

**Comment by fiboknacky** [comment] 2022-11-30 09:17
@RoyBellingan Thanks for letting us know. I've updated the links accordingly.

**Comment by RoyBellingan** [comment] 2022-11-30 17:04
thank you
