### ISSUE TITLE
API returning extra information when not requested

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#409] opened 2020-08-21 15:07 UTC
Hi,

I am using this query
`"SELECT
                        campaign.id,
                        campaign.name,
                        campaign.status,
                        campaign_criterion.location.geo_target_constant,
                        campaign_criterion.language.language_constant
                    FROM
                       campaign_criterion
                    WHERE
                        campaign.id IN (25XXXXX37) `

But API returns devices setting by default, where I have not requested them through Query.

Is this correct response?

Thanks,

**Comment by PierrickVoulet** [comment] 2020-08-24 11:42
@chiragvels I believe this is working as intended because:

* The campaign criterion is what we call the "main resource" (it is specified in the `FROM` clause of your `GAQL` query)
* The resource name of an object always come back regardless of the field selection

This issue does not seem related to the client library but the Google Ads API so I am closing it. If you have further concerns about this behavior, do not hesitate to follow up on the email you already sent to support googleadsapi-support@google.com.

**Closed by PierrickVoulet** 2020-08-24 11:42 UTC
Labels: bug

**Comment by chiragvels** [comment] 2020-08-24 11:57
Hi @PierrickVoulet ,

Thanks, 

So I assume that when using campaign_criteria as main resource It will return all the criteria set?

Ir respective of SELECT fields?

Thanks,

**Comment by PierrickVoulet** [comment] 2020-08-24 12:58
In a `GAQL` query, the selection of the fields you want to retrieve is set by the `SELECT` clause and the filtering is done by with the `WHERE` & `AND` clauses. You will find the full documentation on the Google Ads API developer website [here](https://developers.google.com/google-ads/api/docs/reporting/overview).

The dedicated support for the Google Ads API (googleadsapi-support@google.com) will be able to answer any further questions you may have on this. Do not hesitate to reach out to them.
