### ISSUE TITLE
Service Client Config >> Timeout Milles Method Search

### ISSUE THREAD

**Issue by jeaaas** [googleads/google-ads-php#60] opened 2019-04-24 09:34 UTC
Hi,

I've an error using the calls for the Reporting, using the default parameters of the service client for the method Search.

When I'm using the default **Service Client Config** with the **timeout_millis** to 3600000 it's returning an exception.

The resource that I'm ref. to it's in the json file: google-ads-php\src\Google\Ads\GoogleAds\V1\Services\resources\**google_ads_service_client_config.json**

Setting the timeout_millis param to 600000 it's working.

Please, Could you look into this?

Thank you in advance,
Best,
Jessica

**Comment by Raibaz** [comment] 2019-04-24 11:01
Hi, is this happening with some specific GAQL queries? Can you please send some examples of queries that run into this error?

Also, what exception are you getting?

And also, have you tried setting the `page_size` parameter in your calls to the search function? That may help in reducing the response time of your queries and avoid hitting the timeout.

**Comment by jeaaas** [comment] 2019-04-30 08:46
Hi,

I tried using the query for the campaign: "SELECT campaign.id, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.average_position 
FROM campaign 
WHERE segments.date BETWEEN '2019-04-29' AND '2019-04-29' 
ORDER BY metrics.impressions DESC", setting the page size to 1000.

The exception that returns in this call with the timeout to 360000 is "Timeval expects a long" in the file "grpc\grpc\src\lib\AbstractCall.php" in line 55.

**Comment by Raibaz** [comment] 2019-04-30 11:45
Not sure which part of the configuration you are changing here; are you referring to this?

    "methods": {
        "Search": {
          "timeout_millis": 3600000,
          "retry_codes_name": "non_idempotent",
          "retry_params_name": "default"
        },
        "Mutate": {
          "timeout_millis": 600000,
          "retry_codes_name": "non_idempotent",
          "retry_params_name": "default"
        }
      }

I have been changing both the timeout_millis values here with the values you mentioned but haven't been able to reproduce the error  you are getting.

**Comment by PaoloNardini** [comment] 2019-04-30 13:30
Hi, I'm a Jessica's collegue experiencing the same problem. I can confirm that setting Search timeout_millis to 3,600,000 (default value) raise the exception "Timeval expects a long".
It could be a problem related to Windows X86 version of grpc implementation. 
Grpc Timeval class expects a long value in constructor, while the timeout value is passed as a php int. I'm not sure how to workaround if this is the problem.

**Comment by PaoloNardini** [comment] 2019-04-30 13:50
I have also submitted an Issue to gRPC php library maintainers, in the meanwhile, any chance to set a lower default value to timeout in the next release? It's really needed a 1 hour (!) timeout value? 10 minutes (600 secs) are not enough?

**Comment by Raibaz** [comment] 2019-05-01 10:05
Just to clarify, why are you aiming to reduce the timeout? What issue are you experiencing that made you want to reduce the timeout? There may be an easier solution here.

**Comment by PaoloNardini** [comment] 2019-05-02 07:29
With the default value of 3600000 the gRCP library (windows) raise an exception, reducing the timeout to 600000 all goes ok. What of the above comments in the thread are not clear? It's not a strict Ads Api related problem, it seems to be a problem related to Ads Api vs gRPC, the default timeout value set by API seems to be above the gRPC limit (at least on Windows version).

**Comment by MaksTech** [comment] 2019-05-02 08:54
This is pretty much duplicate of #55 and there's my [explanation](https://github.com/googleads/google-ads-php/issues/55#issuecomment-485881185) to why this is happening.

**Comment by PaoloNardini** [comment] 2019-05-03 07:32
> This is pretty much duplicate of #55 and there's my [explanation](https://github.com/googleads/google-ads-php/issues/55#issuecomment-485881185) to why this is happening.

Thank you very much for your help, this confirm my suspects that it's a problem related to interaction with Windows gRPC library. I cannot find the thread because the exact error message isn't cited in the text of the messages, but only in the screen images.

I just only want to stress again the fact that 1 hour timeout default value is a not real useful value, and using a more realistic value could avoid such kind of problems.
Thank you.

**Comment by Raibaz** [comment] 2019-06-03 10:32
Closing t his due to inactivity.

**Closed by Raibaz** 2019-06-03 10:32 UTC
