### ISSUE TITLE
Library Update to v3 not working

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#287] opened 2020-03-09 09:59 UTC
While Running composer update getting error 
$ php composer.phar update

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating googleads/google-ads-php (v2.2.0 => v3.1.0): Downloading (100%)    The process "unzip -qq  '/var/www/html/codes/vendor/googleads/google-ads-php/5947100af6de4645c987b3dc8a3498c8' -d '/var/www/html/codes/vendor/composer/74aea28d'" exceeded the timeout of 300 seconds.
    **The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)**
    Unzip with unzip command failed, falling back to ZipArchive class

 Update failed (Could not delete /var/www/html/codes/vendor/composer/74aea28d/googleads-google-ads-php-a92d25d/src/Google/Ads/GoogleAds/V3/Resources/Recommendation/CampaignBudgetRecommendation: )

Please check.

Thanks,

**Comment by PierrickVoulet** [comment] 2020-03-09 12:50
Hello @chiragvels - I do not reproduce, this is likely related to the environment. Folks from Composer's project recommend to clear the cache ("--no-cache" option), could you give it a try and let us know if that helps?

**Comment by chiragvels** [comment] 2020-03-12 10:55
I tried to use 
`php composer.phar update --no-cache`
It is not allowed.

**Comment by PierrickVoulet** [comment] 2020-03-12 12:29
This is a [global option](https://getcomposer.org/doc/03-cli.md#global-options) and it worked just fine on my side.

Could you elaborate what you mean by `not allowed`

- Share the error logs
- Share the environment information (e.g. OS, Composer version, PHP version)
- Anything else that you believe is relevant

**Comment by chiragvels** [comment] 2020-03-12 13:38
I mean I was getting this error
  
```
[Symfony\Component\Console\Exception\RuntimeException]  
  The "--no-cache" option does not exist. 
```                
              
PHP verison: PHP 7.3.4 
OS :  Linux 1bea158b97de 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64
Composer version 1.8.0 2018-12-03 10:31:16

I Belive It may be my docker which is creating issue.
I have removed the lib and installed again and it worked.

Thanks,

**Comment by PierrickVoulet** [comment] 2020-03-12 13:44
Thank you for the detail.

I am closing this issue because reinstalling the lib seems to be a valid workaround for such an issue. Feel free to reopen if further concerns on this.

**Closed by PierrickVoulet** 2020-03-12 13:44 UTC
Labels: bug
