### ISSUE TITLE
GetAccountChanges.php Doesn't work

### ISSUE THREAD

**Issue by whyjonii06** [googleads/google-ads-php#70] opened 2019-05-06 09:48 UTC
Hi, i've used your sample code to get the Account Changes.
But i have this response in command line.

`Warning: Grpc\Timeval::__construct() expects parameter 1 to be int, float given in C:\xampp\htdocs\project\vendor\grpc\grpc\src\lib\AbstractCall.php on line 55`
`PHP Fatal error: Uncaught InvalidArgumentException: Timeval expects a long in C:\xampp\htdocs\project\vendor\grpc\grpc\src\lib\AbstractCall.php:55`
`Stack trace:`
`#0 C:\xampp\htdocs\project\vendor\grpc\grpc\src\lib\AbstractCall.php(55): Grpc\Timeval->__construct(3600000000)`
`#1 C:\xampp\htdocs\project\vendor\grpc\grpc\src\lib\DefaultCallInvoker.php(32): Grpc\AbstractCall->__construct(Object(Grpc\Channel), '/google.ads.goo...', Array, Array)`
`#2 C:\xampp\htdocs\project\vendor\grpc\grpc\src\lib\BaseStub.php(259): Grpc\defaultCallInvoker->UnaryCall(Object(Grpc\Channel), '/google.ads.goo...', Array, Array)`
`#3 C:\xampp\htdocs\project\vendor\grpc\grpc\src\lib\BaseStub.php(525): Grpc\BaseStub->Grpc\{closure}('/google.ads.goo...', Object(Google\Ads\GoogleAds\V1\Services\SearchGoogleAdsRequest), Array, Array, Array)`
`#4 C:\xampp\htdocs\project\vendor\google\gax\src\Transport\GrpcTransport.php(212): Grpc\BaseStub->_simpleRequest('/google.ads.goo...', Object(Google\Ads\GoogleAds\V1\Services\SearchGoogleAdsR in C:\xampp\htdocs\project\vendor\grpc\grpc\src\lib\AbstractCall.php on line 55`

**Comment by MaksTech** [comment] 2019-05-07 07:13
Duplicate of #55 and #60 and there's my [explanation](https://github.com/googleads/google-ads-php/issues/55#issuecomment-485881185) to why this is happening.

**Comment by Raibaz** [comment] 2019-05-07 09:43
Yes this looks like the same issue with the gRPC library in a Windows environment.

As suggested by @MaksTech on #55, you can switch to the 64-bit build of PHP to prevent this from happening.

Alternatively, we recently released Docker configuration files in this repo that you can use to run the PHP client library and its examples in a Docker container that already has all dependencies sorted out with the proper versions.

**Closed** 2019-05-28 11:48 UTC
