### ISSUE TITLE
searchStream() is not working

### ISSUE THREAD

**Issue by amitklahiri** [googleads/google-ads-php#304] opened 2020-03-30 20:25 UTC
Hi. 

I am using the latest version of the client library as available using composer install option. I am getting the below error . 

I am using it with PHP Laravel framework. 

Here is my code, 
   ```
 public static function runExample(GoogleAdsClient $googleAdsClient, int $customerId)
    {
        $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
        // Creates a query that retrieves all campaigns.
        $query = 'SELECT campaign.id, campaign.name FROM campaign ORDER BY campaign.id';
        // Issues a search stream request.
        /** @var GoogleAdsServerStreamDecorator $stream */
        $stream = $googleAdsServiceClient->searchStream($customerId, $query);

        // Iterates over all rows in all messages and prints the requested field values for
        // the campaign in each row.
        foreach ($stream->readAll() as $response) {
            /** @var SearchGoogleAdsStreamResponse $response */
            foreach ($response->getResults() as $googleAdsRow) {
                /** @var GoogleAdsRow $googleAdsRow */
                printf(
                    "Campaign with ID %d and name '%s' was found.%s",
                    $googleAdsRow->getCampaign()->getId()->getValue(),
                    $googleAdsRow->getCampaign()->getName()->getValue(),
                    PHP_EOL
                );
            }
        }
    }
```

It looks like getting the error, in this line,
$stream = $googleAdsServiceClient->searchStream($customerId, $query);

And it occurs because the function searchStream(.....), which seems unavailable. 

What am I supposed to do now? Looking forward to solution ASAP. 

Thanks.

**Comment by PierrickVoulet** [comment] 2020-03-30 21:02
Hi @amitklahiri - could you provide more information for us to investigate, e.g.:

- OS
- PHP, Protobuf, gRPC versions used
- Protobuf implementation used ([C or PHP](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf#determine_which_implementation_is_being_used))
- Logs

There are two different methods to search and [streaming](https://developers.google.com/google-ads/api/docs/reporting/streaming) is the one used in this particular code example. Could you give a try with [paging](https://developers.google.com/google-ads/api/docs/reporting/paging) instead? You can refer to the code example [GetAdGroups.php](https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/GetAdGroups.php).

**Comment by fiboknacky** [comment] 2020-03-31 02:35
And, just in case, as you've not included the import statements, please make sure that this line fetches V3 GoogleAdsClient:

```php
$googleAdsClient->getGoogleAdsServiceClient()
```

**Comment by sreenumalae** [comment] 2020-03-31 07:46
In GetCampaigns.php line number 102 and 103 ==>  $stream =$googleAdsServiceClient->searchStream($customerId, $query);

Do we have any option like search instead of searchStream

I have issues in my server i cant add dynamic library 

So, can you please let me know if there is another way without using searchStream.

**Comment by fiboknacky** [comment] 2020-03-31 08:09
`searchStream` is a new feature, but you can still use `search` if you wish.

**Comment by sreenumalae** [comment] 2020-03-31 08:12
Do we need grpc for search?

**Comment by fiboknacky** [comment] 2020-03-31 08:21
gRPC is recommended as always, but you probably can use REST as well.
However, logging is not well supported for REST.

As it seems your issue wouldn't exactly be the same as this issue, could you create a new issue if you have further detail you wish to know more?

**Comment by amitklahiri** [comment] 2020-04-07 20:43
I am using this library with Laravel 6 PHP framework. 

1. I have installed all the require packages as available in this packagist URL. 
https://packagist.org/packages/googleads/google-ads-php

2. But I do not integrate the gRPC to the Laravel separately anywhere. Am I need to do further configuration?

3. Is this library works with the Laravel framework?

**Comment by PierrickVoulet** [comment] 2020-05-01 22:01
I am closing this issue because this seems to be a duplicate of #311 . Feel free to reopen if it is not the case.

**Closed by PierrickVoulet** 2020-05-01 22:01 UTC
Labels: bug, question
