### ISSUE TITLE
General failures trigger partial failures for every operation

### ISSUE THREAD

**Issue by leongersen** [googleads/google-ads-php#495] opened 2020-12-10 08:00 UTC
When sending updates with `partialFailure` set to `true`, general failures trigger partial failures for every operation instead.

For example, when calling `AdGroupCriterionServiceGapicClient::mutateAdGroupCriteria` to update keyword bids, the request might fail, with every individual operation marked with an error `"Too many requests. Retry in 30 seconds."`.

This is a change from the behavior in the former AdWords PHP SDK (where the request throws an exception when exceeding a rate limit), and also seems undocumented. The [documentation on partial failures](https://developers.google.com/google-ads/api/docs/best-practices/partial-failures) and the [accompanying example HandlePartialFailure](https://github.com/googleads/google-ads-php/blob/master/examples/ErrorHandling/HandlePartialFailure.php) indicate that a request with partial failure enabled might still throw `GoogleAdsException` or `ApiException` to be handled, which does not seem to be the case.

In practice, this makes using partial failure for these requests (almost) impossible, because potentially any one of the partial failures could indicate that the entire request should be retried.

**What versions of the client library and Google Ads API are you using?**

V6.0.0 / V6.0.0

**What environment are you using?**

PHP 7.4 and the protobuf extension.

**Actions taken**

Send a request with partial failure enabled.

**Expected result**

The request succeeds, with only the operations with errors triggering a partial failure. If the request cannot or will not be handled, the service call throws an exception.

**Actual result**

A request that cannot/will not be handled succeeds, with every operation marked as partial failure.

**Comment by PierrickVoulet** [comment] 2020-12-11 01:33
Hi @leongersen - If confirmed, this could be an issue with the [Google Ads API](https://developers.google.com/google-ads/api/docs/start) or with our library. Could you provide request IDs (or redacted request and response logs) that illustrate this wrong behavior?

Alternatively, you can contact the Google Ads API [support](https://developers.google.com/google-ads/api/support) if you prefer to confirm what is misbehaving.

**Comment by leongersen** [comment] 2020-12-11 07:22
Hi @PierrickVoulet, here's two requests with this behavior:

**Request ID `CxAuL1wYANmyuc5FDaFAkw`**

All operations failed with:

```Multiple requests were attempting to modify the same resource at once. Please retry the request.```

Logged the following:

```
Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v5.services.AdGroupCriterionService/MutateAdGroupCriteria", CustomerId: <REDACTED>, RequestId: "CxAuL1wYANmyuc5FDaFAkw", IsFault: 0, FaultMessage: "None"
```


**Request ID `HIQegSZ_HGq8hNs_8NQkUQ`**

All operations failed with:

```Too many requests. Retry in 30 seconds.```

Logged the following:

```
Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v5.services.AdGroupCriterionService/MutateAdGroupCriteria", CustomerId: <REDACTED>, RequestId: "HIQegSZ_HGq8hNs_8NQkUQ", IsFault: 0, FaultMessage: "None"
```

**Comment by PierrickVoulet** [comment] 2020-12-11 23:51
Hi @leongersen - Thank you. I took a look at both requests and found that the errors were actually returned as partial errors in the responses from the Google Ads API so I believe that the PHP library worked as intended. The next step is to contact the official [support of Google Ads API](https://developers.google.com/google-ads/api/support) with the details  you provided here so that they can confirm whether this is an expected behavior or not on Google Ads API's side.

I am closing this issue because out of scope but feel free to reopen if a follow up is needed.

**Closed by PierrickVoulet** 2020-12-11 23:51 UTC
Labels: bug

**Comment by leongersen** [comment] 2020-12-14 08:09
Thanks for checking. I've posted the details above to the [Google Ads support group](https://groups.google.com/g/adwords-api/c/j1OIRXnsHWI).
