### ISSUE TITLE
Fail to push limit

### ISSUE THREAD

**Issue by konradstrek** [googleads/google-ads-php#566] opened 2021-03-31 18:46 UTC
Hello!

I'm trying to use `class LinkManagerToClient` on the web version with Google Ads V6, but I'm getting the following error: `Caught exception: Error occurred during parsing: Fail to push limit.`.
In V3 of Google Ads, it worked, but this version has been deprecated. My PHP version: 7.4

`
try {
  return (new GoogleAdsClientBuilder())
   ->fromFile()
   ->withOAuth2Credential($oAuth2Credential)
   ->withLoginCustomerId($loginCustomerId)
   ->build();
} catch (Exception $e) {
  echo 'Caught exception: ',  $e->getMessage(), "\n";
  exit;
}
`

Any information on how to solve it? Thanks.

**Comment by PierrickVoulet** [comment] 2021-03-31 18:58
Hi @konradstrek - It seems to be [related to Protobuf](https://github.com/protocolbuffers/protobuf-php/blob/master/src/Google/Protobuf/Internal/CodedInputStream.php#L340). Could you provide the version of the [`google/protobuf`](https://github.com/googleads/google-ads-php/blob/master/composer.json#L9) package and the version of the `protobuf` PHP Extension if any (running `php -r 'print phpversion("protobuf");'`)?

**Comment by sebastianoffers** [comment] 2021-04-01 08:59
Hello PierrickVoulet. We have exactly the same issue. We using   

-   "php": ">=7.3",
-   "google/gax": "^1.7.0",
-   "grpc/grpc": "^1.36.0",
-   "google/protobuf": "^3.15.0",
-   "monolog/monolog": "^2.0"

thank you for your help. Best regards

**Comment by bytestream** [comment] 2021-05-04 13:42
@PierrickVoulet `Fail to push limit.` can occur if you modify the auto generated protobuf metadata files. For example, if you upload files via an FTP client. Some versions of FileZilla modify line endings, see https://wiki.filezilla-project.org/Data_Type. Removal of any characters from the binary data results in unexpected byte length comparisons. Think of it like serialized data: `s:5:"123"` would fail because the string length is `3` when it was expected to be `5`.

**Comment by steponafish** [comment] 2021-05-04 19:05
Hi @bytestream, I am having this same issue. I uploaded the files via FileZilla. What do I need to do in my settings to prevent removal of any characters from the binary data?

**Comment by bytestream** [comment] 2021-05-04 21:32
@steponafish You can change the transfer data type in FileZilla via the main menu under Transfer -> Transfer type and selecting Binary. Then reupload all the vendor files

**Comment by steponafish** [comment] 2021-05-04 21:52
@bytestream Thank you! I got it to work.

**Comment by PierrickVoulet** [comment] 2021-05-04 23:28
Thank you everyone! I am closing this as it does not seem to be a bug, feel free to reopen with reproduction steps if you believe otherwise.

**Closed by PierrickVoulet** 2021-05-04 23:28 UTC
Labels: bug

**Comment by AshwinParmar** [comment] 2021-08-20 07:33
I am uploading via composer. is there any way to prevent modification of line ending in composer?

**Comment by php4fan** [comment] 2022-01-31 20:05
I reuploaded all the files with Binary mode and it didn't fix the issue.

**Comment by Jatin1903** [comment] 2023-01-09 08:06
I have same issue but not resolve till now please help

**Comment by 14nd90** [comment] 2024-12-20 18:52
@php4fan Also didn't resolve for me. Same issue installing from composer.
