### ISSUE TITLE
Segmentation fault (core dumped) - when calling getGoogleAdsServiceClient()

### ISSUE THREAD

**Issue by emma-brainlabs** [googleads/google-ads-php#403] opened 2020-08-19 12:45 UTC
**Which version of the client library are you using?**
`v4.0.0`

**Which version of PHP are you using?**
`PHP 7.4.9`

**Which operating system (Linux, Windows, ...) and version?**
`Linux 4.15.0-99-generic x86_64`
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"

**Actions taken**
Authorising Google services:
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Google\Ads\GoogleAds\Lib\OAuth2TokenBuilder;
use Google\Ads\GoogleAds\Lib\V4\GoogleAdsClientBuilder;

$adsIniPath = __DIR__."/google_ads_php.ini";

$oAuth2Credential = (new OAuth2TokenBuilder())->fromFile($adsIniPath)->build();

$googleAdsClient = (new GoogleAdsClientBuilder())
    ->fromFile($adsIniPath)
    ->withOAuth2Credential($oAuth2Credential)
    ->build();
$reportingClient = $googleAdsClient->getGoogleAdsServiceClient();
print_r($reportingClient);
```

**Expected result**
Get a reporting client

**Actual result**
I get the error:
```
Segmentation fault (core dumped)
```
I can't find any other logs/prints to give me more details.

**More Information**
This seems to work locally on my computer (Mac OS: 10.14.6) but not on the Linux server (details above).
I think the real issue is that I can't see the proper error/can't see any more detailed information regarding the error -  the lack of information makes it impossible to debug!

**Comment by emma-brainlabs** [comment] 2020-08-19 12:47
My ini file looks like this:
```ini
[GOOGLE_ADS]
; Required some config parameters, which can be found at:
; https://developers.google.com/google-ads/api/docs/first-call/overview#config
developerToken = "REDACTED"

; Required for manager accounts only: Specify the login customer ID used to authenticate API calls.
; This will be the customer ID of the authenticated manager account. You can also specify this later
; in code if your application uses multiple manager account + OAuth pairs.
loginCustomerId = "REDACTED"

; Optional additional settings.
; endpoint = "https://googleads.googleapis.com/"

[OAUTH2]
; Required OAuth2 credentials. Uncomment and fill in the values for the
; appropriate flow based on your use case.

; For installed application flow.
clientId = "REDACTED"
clientSecret = "REDACTED"
refreshToken = "REDACTED"

[LOGGING]
; Optional logging settings.
; logFilePath = "path/to/your/file.log"
; logLevel = "INFO"
```

**Comment by PierrickVoulet** [comment] 2020-08-19 13:09
Hi @emma-brainlabs, the issue is likely due to the line `print_r($reportingClient);` because printing capability does not work consistently while using the protobuf PHP extension. Could you try to remove this line to see if that helps?

Feel free to check our code examples like [`GetCampaigns`](https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/GetCampaigns.php#L103) which uses reporting to get started.

**Comment by emma-brainlabs** [comment] 2020-08-19 13:22
Hi @PierrickVoulet 
I have removed the print statement and the **error is still happening**
The code worked when I was using v1, and I recently upgraded to v4 and it now doesn't work
Note: The code runs on my local machine just fine

**Comment by PierrickVoulet** [comment] 2020-08-19 13:52
Are you using PHP extensions and if yes do you have the right versions installed?

- grpc: the latest version should work just fine as we speak `sudo pecl install grpc`
- protobuf: with v4.0.0, the version 3.11.4 is required `sudo pecl install protobuf-3.11.4`

**Comment by emma-brainlabs** [comment] 2020-08-19 13:57
Hi @PierrickVoulet, Thanks, installing grpc solved it! 🎉 

Should the Google API library output a more clear error that that is the issue here, to allow other users to debug more easily for themselves?

**Comment by PierrickVoulet** [comment] 2020-08-19 14:19
I am glad it worked!

Totally agree, the main problem we are facing is the limitation that composer explains [here](https://getcomposer.org/doc/01-basic-usage.md#platform-packages):

>ext-<name> allows you to require PHP extensions (includes core extensions). Versioning can be quite inconsistent here, so it's often a good idea to set the constraint to *. An example of an extension package name is ext-gd.

@fiboknacky what do you think of having a check at runtime when `GoogleAdsClient` is constructed so we can workaround `composer` limitation? It looks like we could check the `grpc` module version from `phpinfo` for example.

**Comment by fiboknacky** [comment] 2020-08-19 14:29
Let's think about the maintenance cost in the long run as well. 
If there is a certain version that we want to avoid (like > vX.Y.Z), then it's not likely to change. In this case, I think it's no harm to add a check there.
But if it's something that is dynamic, we would need to be careful not to be too strict in some cases.

**Comment by PierrickVoulet** [comment] 2020-08-20 01:14
Good point, I believe it would be mostly useful to check that the installed version is greater than a minimal version. I initiated #406 to follow up on this and I am closing this issue because I consider it resolved.

**Closed by PierrickVoulet** 2020-08-20 01:14 UTC
Labels: bug
