### ISSUE TITLE
ApiException was thrown even after response

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#513] opened 2021-01-12 08:01 UTC
**What versions of the client library and Google Ads API are you using?**
v6

**What environment are you using?**
-PHP 7.2.16-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:42:24) ( NTS )
-ProtoBuf: 3.14.0 (C Implementation)
-gRPC - 1.33.1

**Actions taken**
getting the keywords Ideas

**Expected result**
Keywords with Ideas

**Actual result**
Getting KeywordsIdeas but with ApiException thrown
ApiException was thrown with message '{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": "google.ads.googleads.v6.errors.googleadsfailure-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "grpc-status-details-bin",
            "data": "<Unknown Binary Data>"
        },
        {
            "@type": "request-id",
            "data": "2Qwu9H57ANr_plQ4IUwLGQ"
        }
    ]
}'.

Thanks,

**Comment by chiragvels** [comment] 2021-01-12 08:30
Additional Information:
It is giving me ApiException when add pageSize in argument.

```
[2021-01-12T13:52:29.541455+05:30] google-ads.INFO: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v6.services.KeywordPlanIdeaService/GenerateKeywordIdeas", CustomerId: XXX, RequestId: "fSDak10ZwL1YwKLiNkaNdQ", IsFault: 0, FaultMessage: "None"  
[2021-01-12T13:52:29.880248+05:30] google-ads.WARNING: Request made: Host: "googleads.googleapis.com", Method: "/google.ads.googleads.v6.services.KeywordPlanIdeaService/GenerateKeywordIdeas", CustomerId: XXX, RequestId: "O1Ija_jG_vpuxHOMnvFt3A", IsFault: 1, FaultMessage: "["Page token is invalid."]"  
[2021-01-12T13:52:29.880466+05:30] google-ads.NOTICE: Request
-------
Method Name: /google.ads.googleads.v6.services.KeywordPlanIdeaService/GenerateKeywordIdeas
Host: googleads.googleapis.com
Headers: {
    "x-goog-api-client": "gl-php\/7.2.16-1+ubuntu14.04.1+deb.sury.org+1 gapic\/ gax\/1.7.0 grpc\/1.33.1",
    "x-goog-request-params": "customer_id=XXX",
    "developer-token": "REDACTED"
}
Request: 
{"customerId":"XXX","language":"languageConstants/1000","geoTargetConstants":["geoTargetConstants/1014895"],"pageToken":"CMqAi879sI6gtgEQrAIYsa7Are8uKgJWNkD2CQ","pageSize":300,"keywordPlanNetwork":"GOOGLE_SEARCH_AND_PARTNERS","keywordSeed":{"keywords":["real estate attorney washington dc","real estate lawyer washington dc"]}}

Response
-------
Headers: {
    "request-id": "O1Ija_jG_vpuxHOMnvFt3A",
    "date": "Tue, 12 Jan 2021 08:22:07 GMT",
    "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""
}

Fault
-------
Status code: 3
Details: Request contains an invalid argument.
Failure: {"errors":[{"errorCode":{"requestError":"INVALID_PAGE_TOKEN"},"message":"Page token is invalid."}]}
```

**Comment by PierrickVoulet** [comment] 2021-01-12 19:10
Hi @chiragvels - It looks like the first request works just fine (request ID `fSDak10ZwL1YwKLiNkaNdQ`) but then the second request fails (request ID `O1Ija_jG_vpuxHOMnvFt3A`). Could you provide us with a minimal code snippet to replicate these requests?

**Comment by chiragvels** [comment] 2021-01-13 13:26
Hi @PierrickVoulet ,

Yes, First request was successful, that is why I get the data but next request is called when I add pageSize.
Code snippet:

```
// Generate keyword ideas based on the specified parameters.
        $response = $keywordPlanIdeaServiceClient->generateKeywordIdeas(
            [
                'language' => ResourceNames::forLanguageConstant($languageId),
                'customerId' => $customerId,
                'geoTargetConstants' => $geoTargetConstants,
                'keywordPlanNetwork' => KeywordPlanNetwork::GOOGLE_SEARCH_AND_PARTNERS,
                'pageSize' => self::PAGE_SIZE,
               'keywordAndUrlSeed' => new KeywordAndUrlSeed(['url' => $pageUrl, 'keywords' => $keywords]);
            ] 
        ); 
```

**Comment by PierrickVoulet** [comment] 2021-01-20 01:17
Hi @chiragvels,

I replicated the issue. It is not a bug on our client library but rather on the Google Ads API. I confirmed that the page token used in the request for the second page is the one returned in the response of the first page so it should work just fine.

I reported the bug internally at Google but feel to reach out to the dedicated [support of the Google Ads API](https://developers.google.com/google-ads/api/support) if you need an update about this issue.

I am closing this because it is not in the scope of this repository but feel free to comment.

**Closed by PierrickVoulet** 2021-01-20 01:17 UTC
Labels: bug
