### ISSUE TITLE
How to get the logged in users details of google AdWords account?

### ISSUE THREAD

**Issue by amitlemosys** [googleads/google-ads-php#577] opened 2021-04-24 11:58 UTC
Hello Googlies,

I simply want my users to login my application, once they get logged in, then they could manage their all campaigns from my application.

Could you please guide me?

**Comment by madsem** [comment] 2021-04-24 12:37
Hey, just dis something similar. You're in for a world of pain ;) 

You have to apply for standard access as it sounds like: https://developers.google.com/google-ads/api/docs/access-levels

(during development probably not)

And then since you have users logging in and managing everything you need to implement the RMF for full service tools: https://developers.google.com/google-ads/api/docs/rmf

Which also requires you to use a verified Google Cloud OAuth2 client: https://support.google.com/cloud/answer/9110914?hl=en

Good luck :) Hope you have help, for a single person this is quite a painful process

**Comment by amitlemosys** [comment] 2021-04-24 12:42
:) Thank you so much @madsem 
I have the stander developer token, and made the user logged.
But, I am not able get the all AdWords Accounts' Ids that manages campaigns accordingly.

**Comment by PierrickVoulet** [comment] 2021-04-24 19:04
Hi @amitlemosys - This [guide](https://developers.google.com/google-ads/api/docs/account-management/overview) related to account management should help you to get started. For questions on how the Google Ads API works (not this library specifically), feel free to contact the [Google Ads API support](https://developers.google.com/google-ads/api/support). I am closing this issue because it does not seem to be strictly related to this library but do not hesitate to reopen with information on how to reproduce the issue for us to investigate.

**Closed by PierrickVoulet** 2021-04-24 19:04 UTC
Labels: enhancement

**Comment by ameetroy** [comment] 2021-04-24 21:29
Hi @PierrickVoulet, Thank you very much.
We are making a web application that will do/follow the following functionalities/steps:
    1. User will log in by using their Google AdWord Id.
    2. Once user gets logged In, then they will see their All customers' ids
      
![image](https://user-images.githubusercontent.com/68587477/115973320-b4e92d80-a571-11eb-88f2-7b4a41462949.png)

 3. they will opt their account id.
 4. perform the CRUD operation overall campaigns, Ads, etc.
 
![image](https://user-images.githubusercontent.com/68587477/115973348-01cd0400-a572-11eb-86fd-64f8eb09434f.png)

@PierrickVoulet Please Guide Us.

 Thanks agian

**Comment by PierrickVoulet** [comment] 2021-04-25 14:57
Hi @ameetroy,

Please contact the [Google Ads API support](https://developers.google.com/google-ads/api/support), they will answer all your questions on how to get started with the Google Ads API.

Thanks,
